import csv

drugs = [
    {"brand": "Dolo", "generic": "Paracetamol", "strength": "650 mg"},
    {"brand": "Telma", "generic": "Telmisartan", "strength": "40 mg"},
    {"brand": "Metformin", "generic": "Metformin", "strength": "500 mg"},
    {"brand": "Augmentin", "generic": "Amoxicillin + Clavulanic Acid", "strength": "625 mg"},
    {"brand": "Pan", "generic": "Pantoprazole", "strength": "40 mg"},
    {"brand": "Allegra", "generic": "Fexofenadine", "strength": "120 mg"},
    {"brand": "Thyronorm", "generic": "Thyroxine", "strength": "50 mcg"},
    {"brand": "Amlokind", "generic": "Amlodipine", "strength": "5 mg"},
    {"brand": "Atorva", "generic": "Atorvastatin", "strength": "10 mg"},
    {"brand": "Rosuvas", "generic": "Rosuvastatin", "strength": "10 mg"},
    {"brand": "Clavam", "generic": "Amoxicillin + Clavulanic Acid", "strength": "625 mg"},
    {"brand": "Zerodol-SP", "generic": "Aceclofenac + Serratiopeptidase + Paracetamol", "strength": "100mg/15mg/325mg"},
    {"brand": "Combiflam", "generic": "Ibuprofen + Paracetamol", "strength": "400mg/325mg"},
    {"brand": "Cheston Cold", "generic": "Cetirizine + Paracetamol + Phenylephrine", "strength": "5mg/325mg/10mg"},
    {"brand": "Levocet", "generic": "Levocetirizine", "strength": "5 mg"},
    {"brand": "Montek LC", "generic": "Montelukast + Levocetirizine", "strength": "10mg/5mg"},
    {"brand": "Azithral", "generic": "Azithromycin", "strength": "500 mg"},
    {"brand": "Taxim-O", "generic": "Cefixime", "strength": "200 mg"},
    {"brand": "Oflomac", "generic": "Ofloxacin", "strength": "200 mg"},
    {"brand": "Norflox TZ", "generic": "Norfloxacin + Tinidazole", "strength": "400mg/600mg"},
    {"brand": "Ecosprin", "generic": "Aspirin", "strength": "75 mg"},
    {"brand": "Glycomet", "generic": "Metformin", "strength": "500 mg"},
    {"brand": "Jardiance", "generic": "Empagliflozin", "strength": "10 mg"},
    {"brand": "Jalra", "generic": "Vildagliptin", "strength": "50 mg"},
    {"brand": "Concor", "generic": "Bisoprolol", "strength": "5 mg"},
    {"brand": "Cilacar", "generic": "Cilnidipine", "strength": "10 mg"},
    {"brand": "Tritace", "generic": "Ramipril", "strength": "5 mg"},
    {"brand": "Losar", "generic": "Losartan", "strength": "50 mg"},
    {"brand": "Urimax", "generic": "Tamsulosin", "strength": "0.4 mg"},
    {"brand": "Veltam", "generic": "Tamsulosin", "strength": "0.4 mg"},
    {"brand": "Nexpro", "generic": "Esomeprazole", "strength": "40 mg"},
    {"brand": "Omez", "generic": "Omeprazole", "strength": "20 mg"},
    {"brand": "Rablet", "generic": "Rabeprazole", "strength": "20 mg"},
    {"brand": "Gelusil", "generic": "Aluminium Hydroxide + Magnesium Hydroxide + Simethicone", "strength": "Liquid"},
    {"brand": "Digene", "generic": "Aluminium Hydroxide + Magnesium Hydroxide + Simethicone + Magnesium Aluminium Silicate", "strength": "Tablet"},
    {"brand": "Becosules", "generic": "B-Complex + Vitamin C", "strength": "Capsule"},
    {"brand": "Neurobion Forte", "generic": "Vitamin B Complex", "strength": "Tablet"},
    {"brand": "Evion", "generic": "Vitamin E", "strength": "400 mg"},
    {"brand": "Shelcal", "generic": "Calcium + Vitamin D3", "strength": "500mg/250IU"},
    {"brand": "Orofer XT", "generic": "Ferrous Ascorbate + Folic Acid", "strength": "100mg/1.5mg"},
    {"brand": "Folvite", "generic": "Folic Acid", "strength": "5 mg"},
    {"brand": "Drotin", "generic": "Drotaverine", "strength": "80 mg"},
    {"brand": "Meftal-Spas", "generic": "Mefenamic Acid + Dicyclomine", "strength": "250mg/10mg"},
    {"brand": "Crocin", "generic": "Paracetamol", "strength": "500 mg"},
    {"brand": "Calpol", "generic": "Paracetamol", "strength": "500 mg"},
    {"brand": "Voveran", "generic": "Diclofenac", "strength": "50 mg"},
    {"brand": "Cataflam", "generic": "Diclofenac Potassium", "strength": "50 mg"},
    {"brand": "Flexon", "generic": "Ibuprofen + Paracetamol", "strength": "400mg/325mg"},
    {"brand": "Nimesulide", "generic": "Nimesulide", "strength": "100 mg"},
    {"brand": "Domstal", "generic": "Domperidone", "strength": "10 mg"},
    {"brand": "Ondem", "generic": "Ondansetron", "strength": "4 mg"},
    {"brand": "Stugeron", "generic": "Cinnarizine", "strength": "25 mg"},
    {"brand": "Vertin", "generic": "Betahistine", "strength": "16 mg"},
    {"brand": "Deriphyllin", "generic": "Etofylline + Theophylline", "strength": "77mg/23mg"},
    {"brand": "Asthalin", "generic": "Salbutamol", "strength": "100 mcg/dose"},
    {"brand": "Foracort", "generic": "Formoterol + Budesonide", "strength": "6mcg/200mcg"},
    {"brand": "Duolin", "generic": "Levosalbutamol + Ipratropium", "strength": "1.25mg/500mcg"},
    {"brand": "Seroflo", "generic": "Salmeterol + Fluticasone", "strength": "250 mcg"},
    {"brand": "Ascoril", "generic": "Terbutaline + Bromhexine + Guaifenesin", "strength": "Syrup"},
    {"brand": "Bro-Zedex", "generic": "Terbutaline + Bromhexine + Guaifenesin + Menthol", "strength": "Syrup"},
    {"brand": "Benadryl", "generic": "Diphenhydramine", "strength": "Syrup"},
    {"brand": "Corex", "generic": "Chlorpheniramine + Codeine", "strength": "Syrup"},
    {"brand": "Alex", "generic": "Dextromethorphan + Chlorpheniramine + Phenylephrine", "strength": "Syrup"},
    {"brand": "Betnovate", "generic": "Betamethasone", "strength": "0.1%"},
    {"brand": "Tenovate", "generic": "Clobetasol", "strength": "0.05%"},
    {"brand": "Candid", "generic": "Clotrimazole", "strength": "1%"},
    {"brand": "Lulican", "generic": "Luliconazole", "strength": "1%"},
    {"brand": "Itramac", "generic": "Itraconazole", "strength": "100 mg"},
    {"brand": "Zole", "generic": "Miconazole", "strength": "2%"},
    {"brand": "Soframycin", "generic": "Framycetin", "strength": "1%"},
    {"brand": "T-Bact", "generic": "Mupirocin", "strength": "2%"},
    {"brand": "Volini", "generic": "Diclofenac Diethylamine", "strength": "Gel"},
    {"brand": "Omnigel", "generic": "Diclofenac + Linseed Oil + Menthol + Methyl Salicylate", "strength": "Gel"},
    {"brand": "Relispray", "generic": "Diclofenac + Menthol", "strength": "Spray"},
    {"brand": "Eno", "generic": "Svarjiksara + Nimbukamlam", "strength": "Powder"},
    {"brand": "Cremaffin", "generic": "Liquid Paraffin + Milk of Magnesia", "strength": "Syrup"},
    {"brand": "Dulcolax", "generic": "Bisacodyl", "strength": "5 mg"},
    {"brand": "Looz", "generic": "Lactulose", "strength": "10 g/15ml"},
    {"brand": "Econorm", "generic": "Saccharomyces boulardii", "strength": "250 mg"},
    {"brand": "Enterogermina", "generic": "Bacillus clausii", "strength": "2 Billion Spores"},
    {"brand": "Sporlac", "generic": "Lactic Acid Bacillus", "strength": "Powder"},
    {"brand": "ORS", "generic": "Oral Rehydration Salts", "strength": "Powder"},
    {"brand": "Eldoper", "generic": "Loperamide", "strength": "2 mg"},
    {"brand": "Ativan", "generic": "Lorazepam", "strength": "1 mg"},
    {"brand": "Alprax", "generic": "Alprazolam", "strength": "0.25 mg"},
    {"brand": "Clonotril", "generic": "Clonazepam", "strength": "0.5 mg"},
    {"brand": "Frisium", "generic": "Clobazam", "strength": "10 mg"},
    {"brand": "Zapiz", "generic": "Clonazepam", "strength": "0.5 mg"},
    {"brand": "Meloset", "generic": "Melatonin", "strength": "3 mg"},
    {"brand": "Nurokind", "generic": "Mecobalamin", "strength": "1500 mcg"},
    {"brand": "Pregalin", "generic": "Pregabalin", "strength": "75 mg"},
    {"brand": "Gabapin", "generic": "Gabapentin", "strength": "300 mg"},
    {"brand": "Eptoin", "generic": "Phenytoin", "strength": "100 mg"},
    {"brand": "Tegrital", "generic": "Carbamazepine", "strength": "200 mg"},
    {"brand": "Levipil", "generic": "Levetiracetam", "strength": "500 mg"},
    {"brand": "Zifi", "generic": "Cefixime", "strength": "200 mg"},
    {"brand": "Monocef", "generic": "Ceftriaxone", "strength": "1 g"},
    {"brand": "Moxikind-CV", "generic": "Amoxicillin + Clavulanic Acid", "strength": "625 mg"},
    {"brand": "Cefakind", "generic": "Cefuroxime", "strength": "500 mg"},
    {"brand": "Mahacef", "generic": "Cefixime", "strength": "200 mg"}
]

with open('sample_indian_drugs.csv', mode='w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=["brand", "generic", "strength"])
    writer.writeheader()
    for row in drugs:
        writer.writerow(row)
print("sample_indian_drugs.csv created successfully.")
